### ISSUE TITLE
Something weird with $.

### ISSUE THREAD

**Issue by nevdelap** [nevdelap/ned#55]
Investigate why this works...
```
ned 'savePath=[^\n]*' --replace 'savePath=' .config/Dharkael/flameshot.ini
```
...but while this finds what I expect it to find...
```
ned 'savePath=.*$' .config/Dharkael/flameshot.ini
```
...this doesn't do the replace...
```
ned 'savePath=.*$' --replace 'savePath=' .config/Dharkael/flameshot.ini
```

**Comment by nevdelap** [comment]
I'm writing a smudge script for my .git controlled machine config. Flameshot is a beautiful, beautiful thing.

**Comment by sergeevabc** [comment]
Source.

``` console
$ file file.srt copy.srt
01.srt: UTF-8 Unicode (with BOM) text, with CRLF line terminators
02.srt: UTF-8 Unicode (with BOM) text, with CRLF line terminators

$ cat file.srt
﻿59                                                          
00:05:00,160 --> 00:05:02,720                                
<font color="#ffffff">abc</font>  
<font color="#ffffff">cde</font>                     
                                                             
60                                                           
00:05:05,800 --> 00:05:09,198                                
<font color="#ffff00">fgh</font>            
<font color="#ffff00">ijk</font>
```

Processing with Ned.

``` console                                                        
$ ned -p "(?:<font.*ffffff.*>)([\s\S]*)(?:</font>)" -r $1 file.srt && cat file.srt
﻿﻿59                                                          
00:05:00,160 --> 00:05:02,720                                
  
<font color="#ffffff">cde</font>                     
                                                             
60                                                           
00:05:05,800 --> 00:05:09,198                                
<font color="#ffff00">fgh</font>            
<font color="#ffff00">ijk
```

Aggrrhh! Let’s try with [Ruplacer][1] by @dmerejkowsky.

``` console
$ ruplacer.exe --go "(?:<font.*ffffff.*>)([\s\S]*)(?:</font>)" $1 copy.srt && cat copy.srt
﻿﻿59                                                          
00:05:00,160 --> 00:05:02,720                                
abc  
cde                     
                                                             
60                                                           
00:05:05,800 --> 00:05:09,198                                
<font color="#ffff00">fgh</font>            
<font color="#ffff00">ijk</font>
```

Nice, as expected. But why did Ned fail?

[1]: https://github.com/dmerejkowsky/ruplacer

**Comment by nevdelap** [comment]
Hi Aleksander. I probably won't be able to look closely until after Easter
as I'm away from the computer. First thought though, in the ned version you
are running on Linux?, I think you need to single quote the $1 parameter?
Otherwise it looks like the shell is replacing $1 with empty string so ned
is getting empty string as the replacement parameter for -r instead of the
$1 reference to the group.

**Comment by nevdelap** [comment]
No I don't think it's as simple as that, but I'm just looking at it on my
phone. When I get in the computer next I'll figure it out.

**Comment by nevdelap** [comment]
I think I've got it. It looks like replacer is non greedy by default, ned
is greedy by default.

Testing with https://rustexp.lpil.uk/...

In these screen shots you'll see adding the ? to make the .* Non greedy
makes it find things the way you are expecting. Alternatively you could use
more specific matches than .*.

**Comment by nevdelap** [comment]
In this screenshot here is the rust regex docs. If replacer is being non
greedy by default it seems maybe replacer is doing something that is non
standard regex. But I've never used it.

**Comment by nevdelap** [comment]
The references to screenshots above are me replying but email. After Easter when I'm on the computer I'll add the missing info so that this thread makes sense without them.

**Comment by sergeevabc** [comment]
Nev, thank you for replying on the eve of Easter. Adding ? after each * resolves the issue, but that greedy/non-greedy inconsistency between those search-and-replace apps is going to be a point of eternal anxiety. Warm regards from Russia and God bless you.

```console
$ ned -p "(?:<font.*?ffffff.*?>)([\s\S]*?)(?:</font>)" -r $1 file.srt && cat file.srt
﻿
59                                                          
00:05:00,160 --> 00:05:02,720                                
abc  
cde                     
                                                             
60                                                           
00:05:05,800 --> 00:05:09,198                                
<font color="#ffff00">fgh</font>            
<font color="#ffff00">ijk</font>
```

**Comment by nevdelap** [comment]
You're welcome Aleksander. You can use ned on Windows too. The ned.exe is
there in releases.

**Comment by nevdelap** [comment]
There is probably no real issue here.
