### ISSUE TITLE
Create a brew install ned for OS/X

### ISSUE THREAD

**Issue by ssbarnea** [nevdelap/ned#84]
The de-facto installation method on MacOS is via brew, but there is no recispe or cask for it on MacOS.

Sadly that killed my curiosity to test it. I hope someone will do it.

**Comment by nevdelap** [comment]
Hi Sorin. Sorry, I don't use Macs or know anything about brew or cask. But you only need to download the binary, put it in your path, and chmod +x it. Maybe at some point I'll have a look at a Mac installer for fun. I'll keep the issue open until I do.

**Comment by nevdelap** [comment]
https://ports.macports.org/port/ned/

**Comment by niftylettuce** [comment]
Would love to get this in brew
