### ISSUE TITLE
Feature request: Add some global variable for replacement

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [nevdelap/ned#92]
Ned is basically a find and replace type tool.  Sometimes in the replacements, we need to refer to some information about the file that is being operated on. For example, I may want to find all `{{path}}` and replace with the current file's full path. Other useful information includes the full path of the file, the directory of the file, the file name, file name without suffix, file name extension, etc. I hope you can add some special variables in the replacement to refer to these information. 

My suggestion is, adding the following special variables support in the replacement parameter.
* `{]name[}`, refer to the file name of the file, for example `test.txt`
* `{]fullname[}`, refer to the full name, eg., `c:\path\test.txt`
* `{]path[}`, refer to the path of the file, eg., `c:\path`
* `{]namenosuffix[}`, refer to the name without extension, eg., `test`
* `{]ext[}`, refer to the extension, eg., `txt`

Considering we may need escaped path, an escaped version is also useful. Because sometimes the string `\t` in a path may cause some problems. 
* `{]fullname_esc[}`, refer to the escaped full name, eg., `c:\\path\\test.txt`
* `{]path_esc[}`, refer to the escaped path of the file, eg., `c:\\path`

Btw, why I suggest using the special syntax `{]` and `[}`? It's because they are almost impossible to appear in programming text files as well as normal text files. If you search `"{]"` in the newly launched GitHub search, there are only 9 results, and they all appear either in regex definition or in comments. 

I hope you can consider this request, as this will make ned more useful imo.

**Comment by nevdelap** [comment]
Hi 0x7FFFFFFFFFFFFFFF. This seems like an awfully specific case that you want support for, and it seems odd that a file would need to refer to itself? Not sure in the Windows world, but in the Linux world, if I were to need something like this I'd just write a quick shell script to `find` files, pull their path apart with standard commands, and `ned` replace each one with the path components for the special cases I want to deal with for the thing I need to do at the time.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
That's reasonable. Thanks for the explanation!
