### ISSUE TITLE
Windows and Mac builds

### ISSUE THREAD

**Issue by ktzanev** [nevdelap/ned#93]
> See the README.md for how to do it yourself or reach out to tell me you'd like them. 

It will be nice if you can continue to provide Windows and Mac versions of `ned`. 🚀 
Thanks for your work 🙏

**Comment by nevdelap** [comment]
I used to do it with OS/X in a VirtualBox since I don't have a Mac or use Apple, but it was a little bit too much hassle, but someone has just shown me this: https://github.com/sickcodes/Docker-OSX

So that's a good excuse to do it, and be able to test a cross compiled build done on Linux.

**Comment by kpym** [comment]
May be you can check [ripgrep](https://github.com/BurntSushi/ripgrep), [fd](https://github.com/sharkdp/fd) or other rust tools to see how they use GitHub actions for cross compiling ?
I know (almost) nothing about rust, so I can't help you, sorry.

**Comment by nevdelap** [comment]
Honestly I don't have the time is inclination to mess with Apple or Windows.

**Comment by kpym** [comment]
Ok, I understand. In this case you should probably modify [To Install In Other Linux Distros, Mac OS X, Or Windows](https://github.com/nevdelap/ned#to-install-in-other-linux-distros-mac-os-x-or-windows) section of README : 

> Download the appropriate binary and put it on your path. In Windows install the dependencies as described in the latest release: https://github.com/nevdelap/ned/releases
