### ISSUE TITLE
Correct statement about ripgrep

### ISSUE THREAD

**Issue by kpym** [nevdelap/ned#94]
In the readme [we can read](https://github.com/nevdelap/ned#tldr) : 

> It is the replace that is interesting, which grep and ripgrep cannot do, ...

Which is not true. You can make a replacements with `ripgrep` using the `-r` flag. For example : 

```bash
>  echo "cats are nice" | rg '(cats)' -r 'some $1 and some dogs'
some cats and some dogs are nice
```

**Comment by nevdelap** [comment]
Ok. There was long discussions about adding replace to ripgrep where the author said he didn't want to do it. I'll update. Thanks.

**Comment by nevdelap** [comment]
If I read https://github.com/BurntSushi/ripgrep/issues/74 correctly, it can replace to terminal, but cannot replace in files. Someone also raised https://github.com/BurntSushi/ripgrep/issues/2115 which was closed.

![image](https://user-images.githubusercontent.com/583807/167355870-95656847-3af3-463c-b006-0db261b869de.png)

**Comment by nevdelap** [comment]
I've added some words to clarify, please let me know if it is sufficient. Thanks.

**Comment by kpym** [comment]
Thanks for considering my request. It looks ok for me.
